/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ASelect: typeof import('ant-design-vue')['ASelect']
    ASelectOption: typeof import('ant-design-vue')['ASelectOption']
    Breadcrumb: typeof import('./components/layout/Breadcrumb.vue')['default']
    Card: typeof import('./components/common/Card.vue')['default']
    ChartCard: typeof import('./components/common/ChartCard.vue')['default']
    ChartsOrderStatusChart: typeof import('./components/charts/OrderStatusChart.vue')['default']
    ChartsSalesChart: typeof import('./components/charts/SalesChart.vue')['default']
    ChartsUserGrowthChart: typeof import('./components/charts/UserGrowthChart.vue')['default']
    CommonCard: typeof import('./components/common/Card.vue')['default']
    CommonChartCard: typeof import('./components/common/ChartCard.vue')['default']
    CommonEmptyState: typeof import('./components/common/EmptyState.vue')['default']
    CommonPageHeader: typeof import('./components/common/PageHeader.vue')['default']
    CommonStatCard: typeof import('./components/common/StatCard.vue')['default']
    CommonStatusEditor: typeof import('./components/common/StatusEditor.vue')['default']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    FormComponent: typeof import('./components/form/FormComponent.vue')['default']
    FormFormComponent: typeof import('./components/form/FormComponent.vue')['default']
    LayoutBreadcrumb: typeof import('./components/layout/Breadcrumb.vue')['default']
    LayoutMainLayout: typeof import('./components/layout/MainLayout.vue')['default']
    LayoutSidebar: typeof import('./components/layout/Sidebar.vue')['default']
    LayoutTopNav: typeof import('./components/layout/TopNav.vue')['default']
    MainLayout: typeof import('./components/layout/MainLayout.vue')['default']
    OrderStatusChart: typeof import('./components/charts/OrderStatusChart.vue')['default']
    PageHeader: typeof import('./components/common/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesChart: typeof import('./components/charts/SalesChart.vue')['default']
    Sidebar: typeof import('./components/layout/Sidebar.vue')['default']
    StatCard: typeof import('./components/common/StatCard.vue')['default']
    StatusEditor: typeof import('./components/common/StatusEditor.vue')['default']
    TableComponent: typeof import('./components/table/TableComponent.vue')['default']
    TableTableComponent: typeof import('./components/table/TableComponent.vue')['default']
    TopNav: typeof import('./components/layout/TopNav.vue')['default']
    UserGrowthChart: typeof import('./components/charts/UserGrowthChart.vue')['default']
  }
}
